name: GitVersion

inputs:
  ref:
    required: true
    description: Ref to checkout

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo ${{inputs.ref}}
        echo ${{ github.ref }}